name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16
    
    - name: Prepare
      id: prepare
      run: |
        TAG=${GITHUB_REF#refs/tags/}
        echo ::set-output name=tag_name::${TAG}
    
    - name: Tidy
      run: go mod tidy

    - name: Build
      run: go build -v main.go

    - name: Run GoReleaser
      uses: goreleaser/goreleaser-action@v1
      with:
        version: latest
        args: release --timeout=1h --rm-dist
      env:
        GITHUB_TOKEN: ${{ secrets.ROOT_TOKEN }}
        VERSION: ${{ steps.prepare.outputs.tag_name }}

#     - name: Upload assets
#       uses: actions/upload-artifact@v2
#       with:
#         name: application
#         path: dist/*
    
#     - name: Rename
#       run: mv main adonis_$(go env GOOS)_$(go env GOARCH)
#     - name: Release
#       #uses: actions/upload-release-asset@v1
#       uses: xresloader/upload-to-github-release@v1
#       env:
#         GITHUB_TOKEN: ${{ secrets.ROOT_TOKEN }}
#       with:
#         file: adonis*

